# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortblog', '0002_auto_20171008_0408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user_id']},
        ),
    ]
